apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
  name: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - image: crehm/market-server
        name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-discovery
  name: service-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
      - image: consul
        name: service-discovery

---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery-ui
  labels:
    app: service-discovery-ui
spec:
  type: NodePort
  ports:
    - port: 8500
      nodePort: 31000
  selector:
    app: service-discovery

---
apiVersion: v1
kind: Service
metadata:
  name: discovery-internal
  labels:
    app: discovery-internal
spec:
  type: ClusterIP
  ports:
    - port: 8500
  selector:
    app: service-discovery
---
apiVersion: v1
kind: Service
metadata:
  name: demo-internal
  labels:
    app: demo-internal
spec:
  type: ClusterIP
  ports:
    - port: 8085
  selector:
    app: demo
---
apiVersion: v1
kind: Service
metadata:
  name: demo
  labels:
    app: demo
spec:
  type: NodePort
  ports:
    - port: 8085
      nodePort: 32000
  selector:
    app: demo